apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a3thlu5rc-java-springboot
  janus-idp.io/tekton: a3thlu5rc-java-springboot
  backstage.io/kubernetes-id: a3thlu5rc-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a3thlu5rc-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
